# Generated by Django 5.2.7 on 2025-10-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Биография пока не заполнена', max_length=100),
        ),
    ]
