# Generated by Django 5.2.7 on 2025-10-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
    ]
